#!/bin/bash

set -e

function executable_get()
{
	if [ -r make.exe ]; then
		echo make.exe
	else
		echo make
	fi
}

function prepare()
{
	if [ -d ${TARGET} ]; then
		rm -rf ${TARGET}/
	fi
	d=$(dirname  ${TARGET})
	f=$(basename ${TARGET})
	( cd "$d" && tar xfj $f.tar.bz2 )
}

function step1()
{
	TIME=$(env LANG=en_US date)
	./configure
	HAVE_CONFIGURED=y
	make
	yMAKE=$(executable_get)	
	objcopy -O binary $yMAKE yy-1.bin
	objdump -d $yMAKE > yy-1.asm
}

function step2()
{
	if [ x$HAVE_CONFIGURED != xy ]; then
		./configure
	fi
	HAVE_CONFIGURED=y
	make clean
	../../y-Make --yz-cc=gcc --yz-print-command-line=commands.txt -j1
	yMAKE=$(executable_get)	
	objcopy -O binary $yMAKE yy-2.bin
	objdump -d $yMAKE > yy-2.asm
}

#--------------------------------------------------------------------#
#
#
#--------------------------------------------------------------------#
TARGET=testsuites/make-3.81

prepare
cd ${TARGET}
step1
HAVE_CONFIGURED=y
step2

