#!/bin/sh

set -e

TARGET=make-3.81

if [ -d ${TARGET} ]; then
	rm -rf ${TARGET}/
fi

tar xfj ${TARGET}.tar.bz2

cp pxcc.exe ${TARGET}/

cd ${TARGET}

./configure
make
if [ -r make.exe ]; then
	yMAKE=make.exe
else
	yMAKE=make
fi
objcopy -O binary $yMAKE yy-1.bin

make clean
../pxcc-Make --y-cc=gcc
objcopy -O binary $yMAKE yy-2.bin


