#!/usr/bin/env python2

# vim: tabstop=4 expandtab shiftwidth=4 softtabstop=4

YZ_EXTDIR = 'pyext'

import re, os, sys, getopt, subprocess, signal, time
from distutils import spawn
sys.path.append(os.path.dirname(sys.argv[0]) + '/' + YZ_EXTDIR)
import cu_lib

YZ_CC        = []
YZ_PARSER    = None
YZ_CL_SERVER = None
YZ_SVR_ADDR  = None
YZ_DEP_FILE  = None
YZ_CL_FILE   = None
YZ_SHELL     = "bash"
YZ_IGNORE    = []
YZ_CV_FILE   = None
YZ_PP_SUITE  = None
YZ_SYSBIN    = {}
YZ_TOPDIR    = None
YZ_PJ_FILE   = None
YZ_SHOW_PERF = False
YZ_RT_DIR    = None
YZ_BAK_SUFFIX = '.bak'

def get_ap(x) :
    return os.path.realpath(x)

def get_topdir(make_args) :
    topdir = os.getcwd()
    args = make_args.split()
    for i,a in enumerate(args) :
        if a == '-C' :
            topdir = os.path.realpath(args[i+1])
            break
        elif a.find('-C') == 0 :
            topdir = os.path.realpath(a[2:])
            break
#    print >>sys.stderr, "TOPDIR: %s" % topdir
    return topdir

def generate_cc_scripts() :
    stexts = ''
    for cc in YZ_CC:
        get_sys_bin(cc)
        cc_path = YZ_SYSBIN[cc]

        tmp_args = ' ' + ' '.join(priv_args) + ' --yz-cc=' + cc + ' --yz-verbose=0'
        stexts += 'function ' + cc + '()\n{\n    '
        stexts += YZ_PARSER + tmp_args
        stexts += ' "$@" || return $?\n'
        stexts += '    ' + cc_path
        stexts += ' $*\n}\n'

        cxx = ''
        if re.match(r'gcc$', cc) :
            cxx = cc[0:len(cc)-3] + 'g++'
            get_sys_bin(cxx)
            cxx_path = YZ_SYSBIN[cxx]
            stexts += 'function ' + cxx + '()\n{\n    '
            stexts += YZ_PARSER + tmp_args
            stexts += ' "$@" || return $?\n'
            stexts += '    ' + cxx_path
            stexts += ' $*\n}\n'

        stexts += 'export -f ' + cc + ' ' + cxx + '\n'

    return stexts

def get_sys_bin(name) :
    sb = spawn.find_executable(name)
    if not sb :
        print >>sys.stderr, "%s is required to be installed" % name
        exit(2)
    YZ_SYSBIN[name] = sb

#================================================
#  The main entry
#================================================

get_sys_bin('which')
get_sys_bin('bash')
get_sys_bin('make')

short_options = ''
long_options = (["yz-cc=", "yz-xcc=", 'yz-save-dep=', 'yz-save-cl=', 'yz-save-proj=', 'yz-show-perf', 'yz-runtime-dir=',
    'yz-shell=', 'yz-ignore=', "yz-save-condvals=", "yz-postprocess=", "yz-server-program=", "yz-server-addr=",])

a, make_args = cu_lib.collect_options(short_options, long_options, sys.argv[1:])

try:
    opts, args = getopt.gnu_getopt(a, short_options, long_options)
except getopt.GetoptError as err:
    print >>sys.stderr, str(err)
    exit(2)

for o, a in opts:
    o = o[len('--yz-'):]
    if o == 'cc':
        YZ_CC.append(a)
    elif o == 'xcc':
        YZ_PARSER = get_ap(a)
    elif o.find('save-dep') == 0 :
        YZ_DEP_FILE = get_ap(a)
    elif o == 'save-cl' :
        YZ_CL_FILE = get_ap(a)
    elif o == 'shell' :
        YZ_SHELL = a
    elif o == 'ignore' :
        YZ_IGNORE.append('--yz-ignore=' + a)
    elif o == 'save-condvals':
        YZ_CV_FILE = get_ap(a)
    elif o == 'postprocess':
        YZ_PP_SUITE = get_ap(a)
    elif o == 'save-proj':
        YZ_PJ_FILE = a
    elif o == 'server-program':
        if len(a) > 0 :
            YZ_CL_SERVER = get_ap(a)
    elif o == 'server-addr':
        if len(a) == 0 :
            exit(1)
        YZ_SVR_ADDR = a
    elif o == 'show-perf':
        YZ_SHOW_PERF = True
    elif o == 'runtime-dir':
        YZ_RT_DIR = get_ap(a)

if YZ_PARSER is None:
    YZ_PARSER = get_ap(os.path.dirname(sys.argv[0]) + "/cl.exe")

priv_args = []
csvr_args = []

if YZ_SVR_ADDR is not None :
    if YZ_CL_SERVER is None :
        YZ_CL_SERVER = get_ap(os.path.dirname(sys.argv[0]) + "/cl-server.exe")
    if YZ_SVR_ADDR[0] != '/' :
        if YZ_RT_DIR is not None :
            YZ_SVR_ADDR = get_ap(YZ_RT_DIR + '/' + YZ_SVR_ADDR)
        else :
            YZ_SVR_ADDR = get_ap(YZ_SVR_ADDR)

if YZ_CL_SERVER is not None :
    if YZ_SVR_ADDR is None :
        print >>sys.stderr, "must specify --yz-server-addr"
        exit(1)
    csvr_args += [YZ_CL_SERVER, '--server-addr=' + YZ_SVR_ADDR]
    priv_args.append('--yz-server-addr=' + YZ_SVR_ADDR)

if YZ_PP_SUITE :
    priv_args.append('--yz-no-output')
    if not os.path.exists(YZ_PP_SUITE) :
        os.mkdir(YZ_PP_SUITE)
    if not os.path.isdir(YZ_PP_SUITE) :
        print >>sys.stderr, "Cannot create dir \"%s\"" % YZ_PP_SUITE
        exit(1)
    YZ_DEP_FILE = YZ_PP_SUITE + '/depends.txt'
    YZ_CL_FILE  = YZ_PP_SUITE + '/commands.txt'
    YZ_CV_FILE  = YZ_PP_SUITE + '/condvals.txt'
    YZ_PJ_FILE  = YZ_PP_SUITE + '/projlist.txt'
else :
    priv_args.append('--yz-in-place=' + YZ_BAK_SUFFIX)

if YZ_DEP_FILE is not None :
    priv_args.append('--yz-save-dep=' + YZ_DEP_FILE)
    if YZ_CL_SERVER is None :
        open(YZ_DEP_FILE, "w").close()
    else :
        csvr_args.append('--save-dep=' + YZ_DEP_FILE)

if YZ_CL_FILE is not None :
    priv_args.append('--yz-save-cl=' + YZ_CL_FILE)
    if YZ_CL_SERVER is None :
        open(YZ_CL_FILE, "w").close()
    else :
        csvr_args.append('--save-cl=' + YZ_CL_FILE)

if YZ_CV_FILE :
    priv_args.append('--yz-save-condvals=' + YZ_CV_FILE)
    if YZ_CL_SERVER is None :
        open(YZ_CV_FILE,"w").close()
    else :
        csvr_args.append('--save-condvals=' + YZ_CV_FILE)

if YZ_RT_DIR is not None :
    if not os.path.exists(YZ_RT_DIR) :
        os.mkdir(YZ_RT_DIR)
    priv_args.append('--yz-rt-dir=' + YZ_RT_DIR)
    csvr_args.append('--rt-dir=' + YZ_RT_DIR)

if len(YZ_IGNORE) :
    priv_args += YZ_IGNORE

YZ_TOPDIR = get_topdir(make_args)
if YZ_CV_FILE or YZ_DEP_FILE :
    priv_args.append('--yz-top-dir=' + YZ_TOPDIR)

final_commands =  generate_cc_scripts()
final_commands += YZ_SYSBIN['make']
final_commands += make_args
if YZ_SHELL != None :
    final_commands += ' SHELL=' + YZ_SHELL + ' '
final_commands += '\n'

print final_commands
#exit(2)

sp_svr  = None
sp_make = None

def sigint_handler(sig, frame) :
    if sp_make is not None :
        sp_make.kill()
        sp_make.wait()
    if sp_svr is not None :
        os.kill(sp_svr.pid, signal.SIGUSR1)
        sp_svr.wait()
    sys.exit(1)
signal.signal(signal.SIGINT, sigint_handler)

if YZ_CL_SERVER is not None :
    print "Start sever: %s" % ' '.join(csvr_args)
    sp_svr = subprocess.Popen(csvr_args)
    if sp_svr is None :
        print >>sys.stderr, "Can not start server"
        exit(2)

begin_tm  = time.time()
sp_make = subprocess.Popen(final_commands, shell=True, executable=YZ_SYSBIN['bash'])
sp_make.wait()
if sp_make.returncode :
    exit(sp_make.returncode)
finish_tm = time.time()

if YZ_CL_SERVER is not None :
    os.kill(sp_svr.pid, signal.SIGUSR1)
    sp_svr.wait()
    if sp_svr.returncode :
        print >>sys.stderr, "yMake got error %d" % sp_svr.returncode
        exit(sp_svr.returncode)

if YZ_PP_SUITE :
    print "Post processing ..."
    dir = os.path.realpath(sys.argv[0] + '/../')
    cl = "%s/tools/cl-tool cparse -o %s/tmp.pp %s" % (dir, YZ_PP_SUITE, YZ_CV_FILE)
    subprocess.check_call(cl, shell=True)

    cl = "%s/tools/cl-tool strip %s -f %s/tmp.pp --bak-suffix=%s --all" % (dir, ' '.join(YZ_IGNORE), YZ_PP_SUITE, YZ_BAK_SUFFIX)
    sp_make = subprocess.check_call(cl, shell=True)

if YZ_PJ_FILE :
    pfiles = set()
    fd = open(YZ_DEP_FILE, "r")
    if fd is None :
        print >>sys.stderr, "Cannot open %s for reading" % YZ_DEP_FILE
        exit(2)
    for line in fd :
        fx = line.rstrip('\r\n').split()
        if len(fx) > 0 :
            pfiles.add(fx[0])
    fd.close()

    fd = open(YZ_PJ_FILE, "w")
    print >>fd, '#TOPDIR %s' % YZ_TOPDIR
    for line in pfiles :
        if line.find(YZ_TOPDIR+'/') == 0 :
            print >>fd, line[len(YZ_TOPDIR)+1:]
        else :
            print >>fd, line
    fd.close()

#if YZ_SHOW_PERF :
print "make is excuted during %.2f seconds" % (finish_tm - begin_tm)
